backend:
  name: github
  repo: thaibaole86/newgohub
  base_url: https://api.netlify.com	
  use_graphql: true


media_folder: "images/uploads"
local_backend: true
collections:
  - name: config
    label: Site Configuration
    files:
      - name: config
        label: Site Configuration
        file: site-metadata.json
        fields:
          - widget: string
            name: title
            label: Title
            required: true
          - widget: string
            name: description
            label: Description
            required: true
          - widget: select
            name: palette
            label: Color Palette
            required: true
            hint: The color palette used for the website.
            options:
              - Blue
              - Green
              - Black & White

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "product"
    label: "Product"
    folder: "_products/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Image", name: "thumbnail", widget: "image"}
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Product Price", name: "price", widget: "number"}
      - {label: "Product Description", name: "description", widget: "text"}